<?php
$form ->setElementAttributes('class="form-control"')
      ->setLabelAttributes('class="control-label"')
      ->setErrorAttributes('class="help-block"')
      ->setRowWrapper('div', 'class="form-group"', 'has-error');
?>

<?= $form->open($model->form) ?>

    <?php $form->openFieldset('user') ?>

        <?= $form->row('firstName') ?>
        <?= $form->row('lastName') ?>

        <?= $form->openFieldset('address') ?>

            <?= $form->row('street') ?>
            <?= $form->row('postalCode') ?>
            <?= $form->row('city') ?>
            <?= $form->row('country') ?>

        <?= $form->closeFieldset() ?>

    <?php $form->closeFieldset() ?>

    <?= $form->element('submit', 'value="'.$buttonText.'" class="btn btn-default"') ?>

<?= $form->close() ?>
