<?php
if ($model->success) {
    $route('info')->params('id/'.$model->id)->redirect();
}
$pageTitle = 'Edit User';
$title($pageTitle);
$form ->setElementAttributes('class="form-control"')
      ->setLabelAttributes('class="control-label"')
      ->setErrorAttributes('class="help-block"')
      ->setRowWrapper('div', 'class="form-group"', 'has-error');
?>
<h1><?= $pageTitle ?></h1>

<?= $render(__DIR__.'/partial/form.phtml', ['model' => $model, 'buttonText' => 'Edit' ]) ?>
