<?php
$this->title->suffix(' - Mendo Framework Demo');
$this->js('//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js');
$this->css('//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css');
$this->css('body { padding-top:70px; }');
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo $this->baseUrl; ?>/">Mendo Example Application</a>
        </div>
    </div>
</nav>

<div class="container">
	<?= $this->content() ?>
</div>
